### ISSUE TITLE
Missing 1 required positional argument: 'batch_id'

### ISSUE THREAD

**Issue by itsaark** [fomorians/pyoneer#46]
Hi there,

I tried fixing some of the bugs which I ran into earlier while running the 1st experiment from the tool-use repository. I'm running into another bug with pyoneer. Any help would be greatly appreciated. 

```
File "/Users/School/env/lib/python3.6/site-packages/pyoneer/rl/wrappers/batch_impl.py", line 43, in <listcomp>
    self.envs = [constructor() for _ in range(batch_size)]
TypeError: <lambda>() missing 1 required positional argument: 'batch_id'

```

**Comment by jimfleming** [comment]
Hello, Thanks for checking out the project! We're actively developing pyoneer and we likely introduced an incompatibility with the tool-use project. We'll take a look.

**Comment by jimfleming** [comment]
Hi @itsaark, I believe this issue is occurring because the version of pyoneer you have installed constructs environments without the batch id. If you're installed pyoneer locally, please check out the `v0.2` tag.

Closing this issue for now but if you run into more issues feel free to reply back here or open another issue.

**Comment by itsaark** [comment]
> Hello, Thanks for checking out the project! We're actively developing pyoneer and we likely introduced an incompatibility with the tool-use project. We'll take a look.

I understand. Thanks so much for the quick fix @jimfleming. Appreciate your help!
